import type { FormTemplate } from '@medicore/contracts';

export const ORL_PHYSICAL_EXAM_TEMPLATE: FormTemplate = {
  id: 'orl-physical-exam-v1',
  name: 'Exploración ORL',
  specialty: 'ORL',
  version: '1.0.0',
  fields: [
    {
      type: 'section',
      id: 's-ear',
      title: 'Oídos',
      collapsible: true,
    },
    {
      type: 'select',
      id: 'otoscopy_right_membrane',
      label: 'Membrana timpánica derecha',
      options: [
        { value: 'intact', label: 'Íntegra' },
        { value: 'retracted', label: 'Retraída' },
        { value: 'perforated', label: 'Perforada' },
        { value: 'not_visible', label: 'No visible' },
      ],
      required: false,
    },
    {
      type: 'text',
      id: 'otoscopy_right_notes',
      label: 'Notas oído derecho',
      multiline: true,
      required: false,
    },
    {
      type: 'select',
      id: 'otoscopy_left_membrane',
      label: 'Membrana timpánica izquierda',
      options: [
        { value: 'intact', label: 'Íntegra' },
        { value: 'retracted', label: 'Retraída' },
        { value: 'perforated', label: 'Perforada' },
        { value: 'not_visible', label: 'No visible' },
      ],
      required: false,
    },
    {
      type: 'text',
      id: 'otoscopy_left_notes',
      label: 'Notas oído izquierdo',
      multiline: true,
      required: false,
    },
    {
      type: 'section',
      id: 's-nose',
      title: 'Nariz y senos paranasales',
      collapsible: true,
    },
    {
      type: 'select',
      id: 'septum',
      label: 'Tabique nasal',
      options: [
        { value: 'centered', label: 'Centrado' },
        { value: 'deviated_right', label: 'Desviado derecha' },
        { value: 'deviated_left', label: 'Desviado izquierda' },
        { value: 'irregular', label: 'Irregular' },
      ],
      required: false,
    },
    {
      type: 'text',
      id: 'rhinoscopy_notes',
      label: 'Rinoscopia',
      multiline: true,
      required: false,
    },
    {
      type: 'section',
      id: 's-throat',
      title: 'Orofaringe',
      collapsible: true,
    },
    {
      type: 'select',
      id: 'tonsils',
      label: 'Amígdalas',
      options: [
        { value: 'normal', label: 'Normales' },
        { value: 'grade_1', label: 'Grado I' },
        { value: 'grade_2', label: 'Grado II' },
        { value: 'grade_3', label: 'Grado III' },
        { value: 'grade_4', label: 'Grado IV' },
        { value: 'absent', label: 'Ausentes' },
      ],
      required: false,
    },
    {
      type: 'text',
      id: 'oropharynx_notes',
      label: 'Notas orofaringe',
      multiline: true,
      required: false,
    },
    {
      type: 'section',
      id: 's-larynx',
      title: 'Laringe',
      collapsible: true,
    },
    {
      type: 'text',
      id: 'laryngoscopy_notes',
      label: 'Laringoscopia',
      multiline: true,
      required: false,
    },
    {
      type: 'section',
      id: 's-neck',
      title: 'Cuello',
      collapsible: true,
    },
    {
      type: 'select',
      id: 'lymph_nodes',
      label: 'Adenopatías',
      options: [
        { value: 'not_palpable', label: 'No palpables' },
        { value: 'submandibular', label: 'Submandibular' },
        { value: 'cervical_anterior', label: 'Cervical anterior' },
        { value: 'cervical_posterior', label: 'Cervical posterior' },
        { value: 'multiple', label: 'Múltiples' },
      ],
      required: false,
    },
    {
      type: 'text',
      id: 'neck_notes',
      label: 'Notas cuello',
      multiline: true,
      required: false,
    },
  ],
};
