import type { CodeEntry } from '../types';

export const icd10Catalog: CodeEntry[] = [
  // H60-H62: Otitis externa
  { system: 'ICD10', code: 'H60.0', description: 'Absceso del oído externo', chapter: 'H60-H95', parentCode: 'H60' },
  { system: 'ICD10', code: 'H60.1', description: 'Celulitis del oído externo', chapter: 'H60-H95', parentCode: 'H60' },
  { system: 'ICD10', code: 'H60.2', description: 'Otitis externa maligna', chapter: 'H60-H95', parentCode: 'H60' },
  { system: 'ICD10', code: 'H60.3', description: 'Otitis externa difusa', chapter: 'H60-H95', parentCode: 'H60' },
  { system: 'ICD10', code: 'H60.4', description: 'Colesteatoma del oído externo', chapter: 'H60-H95', parentCode: 'H60' },
  { system: 'ICD10', code: 'H60.5', description: 'Otitis externa aguda no infecciosa', chapter: 'H60-H95', parentCode: 'H60' },
  { system: 'ICD10', code: 'H60.8', description: 'Otras otitis externas', chapter: 'H60-H95', parentCode: 'H60' },
  { system: 'ICD10', code: 'H60.9', description: 'Otitis externa no especificada', chapter: 'H60-H95', parentCode: 'H60' },
  { system: 'ICD10', code: 'H61.0', description: 'Pericondritis del oído externo', chapter: 'H60-H95', parentCode: 'H61' },
  { system: 'ICD10', code: 'H61.1', description: 'Deformidad adquirida del pabellón auricular', chapter: 'H60-H95', parentCode: 'H61' },
  { system: 'ICD10', code: 'H61.2', description: 'Tapón de cerumen', chapter: 'H60-H95', parentCode: 'H61' },
  { system: 'ICD10', code: 'H61.3', description: 'Estenosis adquirida del conducto auditivo externo', chapter: 'H60-H95', parentCode: 'H61' },
  { system: 'ICD10', code: 'H61.8', description: 'Otros trastornos del oído externo', chapter: 'H60-H95', parentCode: 'H61' },
  { system: 'ICD10', code: 'H61.9', description: 'Trastorno del oído externo no especificado', chapter: 'H60-H95', parentCode: 'H61' },
  { system: 'ICD10', code: 'H62.0', description: 'Otitis externa en enfermedades bacterianas', chapter: 'H60-H95', parentCode: 'H62' },
  { system: 'ICD10', code: 'H62.1', description: 'Otitis externa en enfermedades virales', chapter: 'H60-H95', parentCode: 'H62' },
  { system: 'ICD10', code: 'H62.2', description: 'Otitis externa en micosis', chapter: 'H60-H95', parentCode: 'H62' },
  { system: 'ICD10', code: 'H62.3', description: 'Otitis externa en otras enfermedades infecciosas', chapter: 'H60-H95', parentCode: 'H62' },
  { system: 'ICD10', code: 'H62.4', description: 'Otitis externa en otras enfermedades clasificadas', chapter: 'H60-H95', parentCode: 'H62' },

  // H65-H67: Otitis media no supurativa
  { system: 'ICD10', code: 'H65.0', description: 'Otitis media serosa aguda', chapter: 'H60-H95', parentCode: 'H65' },
  { system: 'ICD10', code: 'H65.1', description: 'Otitis media aguda no supurativa', chapter: 'H60-H95', parentCode: 'H65' },
  { system: 'ICD10', code: 'H65.2', description: 'Otitis media serosa crónica', chapter: 'H60-H95', parentCode: 'H65' },
  { system: 'ICD10', code: 'H65.3', description: 'Otitis media mucoide crónica', chapter: 'H60-H95', parentCode: 'H65' },
  { system: 'ICD10', code: 'H65.4', description: 'Otitis media crónica no supurativa', chapter: 'H60-H95', parentCode: 'H65' },
  { system: 'ICD10', code: 'H65.9', description: 'Otitis media no supurativa sin especificar', chapter: 'H60-H95', parentCode: 'H65' },
  { system: 'ICD10', code: 'H66.0', description: 'Otitis media supurativa aguda', chapter: 'H60-H95', parentCode: 'H66' },
  { system: 'ICD10', code: 'H66.1', description: 'Otitis media supurativa crónica tubotimpánica', chapter: 'H60-H95', parentCode: 'H66' },
  { system: 'ICD10', code: 'H66.2', description: 'Otitis media supurativa crónica aticoantral', chapter: 'H60-H95', parentCode: 'H66' },
  { system: 'ICD10', code: 'H66.3', description: 'Otitis media crónica supurativa sin especificar', chapter: 'H60-H95', parentCode: 'H66' },
  { system: 'ICD10', code: 'H66.4', description: 'Otitis media supurativa no especificada', chapter: 'H60-H95', parentCode: 'H66' },
  { system: 'ICD10', code: 'H66.9', description: 'Otitis media no especificada', chapter: 'H60-H95', parentCode: 'H66' },
  { system: 'ICD10', code: 'H67.0', description: 'Otitis media en enfermedades bacterianas', chapter: 'H60-H95', parentCode: 'H67' },
  { system: 'ICD10', code: 'H67.1', description: 'Otitis media en enfermedades virales', chapter: 'H60-H95', parentCode: 'H67' },
  { system: 'ICD10', code: 'H67.8', description: 'Otitis media en otras enfermedades', chapter: 'H60-H95', parentCode: 'H67' },

  // H70-H74: Mastoiditis y afecciones relacionadas
  { system: 'ICD10', code: 'H70.0', description: 'Mastoiditis aguda', chapter: 'H60-H95', parentCode: 'H70' },
  { system: 'ICD10', code: 'H70.1', description: 'Mastoiditis crónica', chapter: 'H60-H95', parentCode: 'H70' },
  { system: 'ICD10', code: 'H70.2', description: 'Petrositis', chapter: 'H60-H95', parentCode: 'H70' },
  { system: 'ICD10', code: 'H70.8', description: 'Otras mastoiditis y afecciones relacionadas', chapter: 'H60-H95', parentCode: 'H70' },
  { system: 'ICD10', code: 'H70.9', description: 'Mastoiditis no especificada', chapter: 'H60-H95', parentCode: 'H70' },
  { system: 'ICD10', code: 'H71', description: 'Colesteatoma del oído medio', chapter: 'H60-H95' },
  { system: 'ICD10', code: 'H72.0', description: 'Perforación timpánica central', chapter: 'H60-H95', parentCode: 'H72' },
  { system: 'ICD10', code: 'H72.1', description: 'Perforación timpánica atical', chapter: 'H60-H95', parentCode: 'H72' },
  { system: 'ICD10', code: 'H72.2', description: 'Otras perforaciones marginales del tímpano', chapter: 'H60-H95', parentCode: 'H72' },
  { system: 'ICD10', code: 'H72.8', description: 'Otras perforaciones de la membrana timpánica', chapter: 'H60-H95', parentCode: 'H72' },
  { system: 'ICD10', code: 'H72.9', description: 'Perforación de la membrana timpánica no especificada', chapter: 'H60-H95', parentCode: 'H72' },
  { system: 'ICD10', code: 'H73.0', description: 'Miringitis aguda', chapter: 'H60-H95', parentCode: 'H73' },
  { system: 'ICD10', code: 'H73.1', description: 'Miringitis crónica', chapter: 'H60-H95', parentCode: 'H73' },
  { system: 'ICD10', code: 'H73.8', description: 'Otros trastornos de la membrana timpánica', chapter: 'H60-H95', parentCode: 'H73' },
  { system: 'ICD10', code: 'H73.9', description: 'Trastorno de la membrana timpánica no especificado', chapter: 'H60-H95', parentCode: 'H73' },
  { system: 'ICD10', code: 'H74.0', description: 'Timpanoesclerosis', chapter: 'H60-H95', parentCode: 'H74' },
  { system: 'ICD10', code: 'H74.1', description: 'Enfermedad adhesiva del oído medio', chapter: 'H60-H95', parentCode: 'H74' },
  { system: 'ICD10', code: 'H74.2', description: 'Discontinuidad de la cadena de huesecillos', chapter: 'H60-H95', parentCode: 'H74' },
  { system: 'ICD10', code: 'H74.3', description: 'Otras anormalidades adquiridas de los huesecillos', chapter: 'H60-H95', parentCode: 'H74' },
  { system: 'ICD10', code: 'H74.4', description: 'Pólipo del oído medio', chapter: 'H60-H95', parentCode: 'H74' },
  { system: 'ICD10', code: 'H74.8', description: 'Otros trastornos del oído medio y mastoides', chapter: 'H60-H95', parentCode: 'H74' },
  { system: 'ICD10', code: 'H74.9', description: 'Trastorno del oído medio y mastoides no especificado', chapter: 'H60-H95', parentCode: 'H74' },

  // H80-H82: Otosclerosis
  { system: 'ICD10', code: 'H80.0', description: 'Otosclerosis que afecta la ventana oval no obliterante', chapter: 'H60-H95', parentCode: 'H80' },
  { system: 'ICD10', code: 'H80.1', description: 'Otosclerosis que afecta la ventana oval obliterante', chapter: 'H60-H95', parentCode: 'H80' },
  { system: 'ICD10', code: 'H80.2', description: 'Otosclerosis coclear', chapter: 'H60-H95', parentCode: 'H80' },
  { system: 'ICD10', code: 'H80.8', description: 'Otras otosclerosis', chapter: 'H60-H95', parentCode: 'H80' },
  { system: 'ICD10', code: 'H80.9', description: 'Otosclerosis no especificada', chapter: 'H60-H95', parentCode: 'H80' },
  { system: 'ICD10', code: 'H81.0', description: 'Enfermedad de Ménière', chapter: 'H60-H95', parentCode: 'H81' },
  { system: 'ICD10', code: 'H81.1', description: 'Vértigo paroxístico benigno', chapter: 'H60-H95', parentCode: 'H81' },
  { system: 'ICD10', code: 'H81.2', description: 'Neuronitis vestibular', chapter: 'H60-H95', parentCode: 'H81' },
  { system: 'ICD10', code: 'H81.3', description: 'Otros vértigos periféricos', chapter: 'H60-H95', parentCode: 'H81' },
  { system: 'ICD10', code: 'H81.4', description: 'Vértigo de origen central', chapter: 'H60-H95', parentCode: 'H81' },
  { system: 'ICD10', code: 'H81.8', description: 'Otros trastornos de la función vestibular', chapter: 'H60-H95', parentCode: 'H81' },
  { system: 'ICD10', code: 'H81.9', description: 'Trastorno de la función vestibular no especificado', chapter: 'H60-H95', parentCode: 'H81' },
  { system: 'ICD10', code: 'H82', description: 'Síndromes vertiginosos en enfermedades clasificadas', chapter: 'H60-H95' },

  // H83: Otras enfermedades del oído interno
  { system: 'ICD10', code: 'H83.0', description: 'Laberintitis', chapter: 'H60-H95', parentCode: 'H83' },
  { system: 'ICD10', code: 'H83.1', description: 'Fístula del laberinto', chapter: 'H60-H95', parentCode: 'H83' },
  { system: 'ICD10', code: 'H83.2', description: 'Disfunción del laberinto', chapter: 'H60-H95', parentCode: 'H83' },
  { system: 'ICD10', code: 'H83.3', description: 'Efectos del ruido sobre el oído interno', chapter: 'H60-H95', parentCode: 'H83' },
  { system: 'ICD10', code: 'H83.8', description: 'Otras enfermedades del oído interno', chapter: 'H60-H95', parentCode: 'H83' },
  { system: 'ICD10', code: 'H83.9', description: 'Enfermedad del oído interno no especificada', chapter: 'H60-H95', parentCode: 'H83' },

  // H90-H91: Hipoacusia
  { system: 'ICD10', code: 'H90.0', description: 'Hipoacusia conductiva bilateral', chapter: 'H60-H95', parentCode: 'H90' },
  { system: 'ICD10', code: 'H90.1', description: 'Hipoacusia conductiva unilateral con audición normal contralateral', chapter: 'H60-H95', parentCode: 'H90' },
  { system: 'ICD10', code: 'H90.2', description: 'Hipoacusia conductiva sin especificar', chapter: 'H60-H95', parentCode: 'H90' },
  { system: 'ICD10', code: 'H90.3', description: 'Hipoacusia neurosensorial bilateral', chapter: 'H60-H95', parentCode: 'H90' },
  { system: 'ICD10', code: 'H90.4', description: 'Hipoacusia neurosensorial unilateral con audición normal contralateral', chapter: 'H60-H95', parentCode: 'H90' },
  { system: 'ICD10', code: 'H90.5', description: 'Hipoacusia neurosensorial sin especificar', chapter: 'H60-H95', parentCode: 'H90' },
  { system: 'ICD10', code: 'H90.6', description: 'Hipoacusia mixta conductiva y neurosensorial bilateral', chapter: 'H60-H95', parentCode: 'H90' },
  { system: 'ICD10', code: 'H90.7', description: 'Hipoacusia mixta conductiva y neurosensorial unilateral', chapter: 'H60-H95', parentCode: 'H90' },
  { system: 'ICD10', code: 'H90.8', description: 'Hipoacusia mixta conductiva y neurosensorial sin especificar', chapter: 'H60-H95', parentCode: 'H90' },
  { system: 'ICD10', code: 'H91.0', description: 'Hipoacusia ototóxica', chapter: 'H60-H95', parentCode: 'H91' },
  { system: 'ICD10', code: 'H91.1', description: 'Presbiacusia', chapter: 'H60-H95', parentCode: 'H91' },
  { system: 'ICD10', code: 'H91.2', description: 'Hipoacusia súbita idiopática', chapter: 'H60-H95', parentCode: 'H91' },
  { system: 'ICD10', code: 'H91.3', description: 'Sordomudez no clasificada en otra parte', chapter: 'H60-H95', parentCode: 'H91' },
  { system: 'ICD10', code: 'H91.8', description: 'Otras hipoacusias especificadas', chapter: 'H60-H95', parentCode: 'H91' },
  { system: 'ICD10', code: 'H91.9', description: 'Hipoacusia no especificada', chapter: 'H60-H95', parentCode: 'H91' },

  // H92-H93: Otalgia y otros síntomas del oído
  { system: 'ICD10', code: 'H92.0', description: 'Otalgia', chapter: 'H60-H95', parentCode: 'H92' },
  { system: 'ICD10', code: 'H92.1', description: 'Otorrea', chapter: 'H60-H95', parentCode: 'H92' },
  { system: 'ICD10', code: 'H92.2', description: 'Otorragia', chapter: 'H60-H95', parentCode: 'H92' },
  { system: 'ICD10', code: 'H93.0', description: 'Trastornos degenerativos y vasculares del oído interno', chapter: 'H60-H95', parentCode: 'H93' },
  { system: 'ICD10', code: 'H93.1', description: 'Tinnitus', chapter: 'H60-H95', parentCode: 'H93' },
  { system: 'ICD10', code: 'H93.2', description: 'Otras percepciones auditivas anormales', chapter: 'H60-H95', parentCode: 'H93' },
  { system: 'ICD10', code: 'H93.3', description: 'Trastornos del nervio auditivo', chapter: 'H60-H95', parentCode: 'H93' },
  { system: 'ICD10', code: 'H93.8', description: 'Otros trastornos especificados del oído', chapter: 'H60-H95', parentCode: 'H93' },
  { system: 'ICD10', code: 'H93.9', description: 'Trastorno del oído no especificado', chapter: 'H60-H95', parentCode: 'H93' },

  // H94: Trastornos del oído en enfermedades clasificadas
  { system: 'ICD10', code: 'H94.0', description: 'Neuritis del nervio auditivo en enfermedades infecciosas', chapter: 'H60-H95', parentCode: 'H94' },
  { system: 'ICD10', code: 'H94.8', description: 'Otros trastornos del oído en enfermedades clasificadas', chapter: 'H60-H95', parentCode: 'H94' },

  // J00-J06: Infecciones agudas de vías respiratorias superiores
  { system: 'ICD10', code: 'J00', description: 'Rinofaringitis aguda (resfriado común)', chapter: 'J00-J06' },
  { system: 'ICD10', code: 'J01.0', description: 'Sinusitis maxilar aguda', chapter: 'J00-J06', parentCode: 'J01' },
  { system: 'ICD10', code: 'J01.1', description: 'Sinusitis frontal aguda', chapter: 'J00-J06', parentCode: 'J01' },
  { system: 'ICD10', code: 'J01.2', description: 'Sinusitis etmoidal aguda', chapter: 'J00-J06', parentCode: 'J01' },
  { system: 'ICD10', code: 'J01.3', description: 'Sinusitis esfenoidal aguda', chapter: 'J00-J06', parentCode: 'J01' },
  { system: 'ICD10', code: 'J01.4', description: 'Pansinusitis aguda', chapter: 'J00-J06', parentCode: 'J01' },
  { system: 'ICD10', code: 'J01.8', description: 'Otras sinusitis agudas', chapter: 'J00-J06', parentCode: 'J01' },
  { system: 'ICD10', code: 'J01.9', description: 'Sinusitis aguda no especificada', chapter: 'J00-J06', parentCode: 'J01' },
  { system: 'ICD10', code: 'J02.0', description: 'Faringitis estreptocócica', chapter: 'J00-J06', parentCode: 'J02' },
  { system: 'ICD10', code: 'J02.8', description: 'Faringitis aguda por otros organismos', chapter: 'J00-J06', parentCode: 'J02' },
  { system: 'ICD10', code: 'J02.9', description: 'Faringitis aguda no especificada', chapter: 'J00-J06', parentCode: 'J02' },
  { system: 'ICD10', code: 'J03.0', description: 'Amigdalitis estreptocócica', chapter: 'J00-J06', parentCode: 'J03' },
  { system: 'ICD10', code: 'J03.8', description: 'Amigdalitis aguda por otros organismos', chapter: 'J00-J06', parentCode: 'J03' },
  { system: 'ICD10', code: 'J03.9', description: 'Amigdalitis aguda no especificada', chapter: 'J00-J06', parentCode: 'J03' },
  { system: 'ICD10', code: 'J04.0', description: 'Laringitis aguda', chapter: 'J00-J06', parentCode: 'J04' },
  { system: 'ICD10', code: 'J04.1', description: 'Traqueítis aguda', chapter: 'J00-J06', parentCode: 'J04' },
  { system: 'ICD10', code: 'J04.2', description: 'Laringotraqueítis aguda', chapter: 'J00-J06', parentCode: 'J04' },
  { system: 'ICD10', code: 'J05.0', description: 'Laringitis obstructiva aguda (crup)', chapter: 'J00-J06', parentCode: 'J05' },
  { system: 'ICD10', code: 'J05.1', description: 'Epiglotitis aguda', chapter: 'J00-J06', parentCode: 'J05' },
  { system: 'ICD10', code: 'J06.0', description: 'Laringofaringitis aguda', chapter: 'J00-J06', parentCode: 'J06' },
  { system: 'ICD10', code: 'J06.8', description: 'Otras infecciones agudas de sitios múltiples de vías respiratorias superiores', chapter: 'J00-J06', parentCode: 'J06' },
  { system: 'ICD10', code: 'J06.9', description: 'Infección aguda de vías respiratorias superiores no especificada', chapter: 'J00-J06', parentCode: 'J06' },

  // J30-J39: Otras enfermedades de vías respiratorias superiores
  { system: 'ICD10', code: 'J30.0', description: 'Rinitis vasomotora', chapter: 'J30-J39', parentCode: 'J30' },
  { system: 'ICD10', code: 'J30.1', description: 'Rinitis alérgica por polen', chapter: 'J30-J39', parentCode: 'J30' },
  { system: 'ICD10', code: 'J30.2', description: 'Rinitis alérgica estacional', chapter: 'J30-J39', parentCode: 'J30' },
  { system: 'ICD10', code: 'J30.3', description: 'Rinitis alérgica perenne', chapter: 'J30-J39', parentCode: 'J30' },
  { system: 'ICD10', code: 'J30.4', description: 'Rinitis alérgica no especificada', chapter: 'J30-J39', parentCode: 'J30' },
  { system: 'ICD10', code: 'J31.0', description: 'Rinitis crónica', chapter: 'J30-J39', parentCode: 'J31' },
  { system: 'ICD10', code: 'J31.1', description: 'Nasofaringitis crónica', chapter: 'J30-J39', parentCode: 'J31' },
  { system: 'ICD10', code: 'J31.2', description: 'Faringitis crónica', chapter: 'J30-J39', parentCode: 'J31' },
  { system: 'ICD10', code: 'J32.0', description: 'Sinusitis maxilar crónica', chapter: 'J30-J39', parentCode: 'J32' },
  { system: 'ICD10', code: 'J32.1', description: 'Sinusitis frontal crónica', chapter: 'J30-J39', parentCode: 'J32' },
  { system: 'ICD10', code: 'J32.2', description: 'Sinusitis etmoidal crónica', chapter: 'J30-J39', parentCode: 'J32' },
  { system: 'ICD10', code: 'J32.3', description: 'Sinusitis esfenoidal crónica', chapter: 'J30-J39', parentCode: 'J32' },
  { system: 'ICD10', code: 'J32.4', description: 'Pansinusitis crónica', chapter: 'J30-J39', parentCode: 'J32' },
  { system: 'ICD10', code: 'J32.8', description: 'Otras sinusitis crónicas', chapter: 'J30-J39', parentCode: 'J32' },
  { system: 'ICD10', code: 'J32.9', description: 'Sinusitis crónica no especificada', chapter: 'J30-J39', parentCode: 'J32' },
  { system: 'ICD10', code: 'J33.0', description: 'Pólipo de la cavidad nasal', chapter: 'J30-J39', parentCode: 'J33' },
  { system: 'ICD10', code: 'J33.1', description: 'Degeneración polipoide del seno paranasal', chapter: 'J30-J39', parentCode: 'J33' },
  { system: 'ICD10', code: 'J33.8', description: 'Otros pólipos de los senos paranasales', chapter: 'J30-J39', parentCode: 'J33' },
  { system: 'ICD10', code: 'J33.9', description: 'Pólipo nasal no especificado', chapter: 'J30-J39', parentCode: 'J33' },
  { system: 'ICD10', code: 'J34.0', description: 'Absceso, furúnculo o ántrax de la nariz', chapter: 'J30-J39', parentCode: 'J34' },
  { system: 'ICD10', code: 'J34.1', description: 'Quiste o mucocele de la nariz y seno paranasal', chapter: 'J30-J39', parentCode: 'J34' },
  { system: 'ICD10', code: 'J34.2', description: 'Desviación del tabique nasal', chapter: 'J30-J39', parentCode: 'J34' },
  { system: 'ICD10', code: 'J34.3', description: 'Hipertrofia de los cornetes nasales', chapter: 'J30-J39', parentCode: 'J34' },
  { system: 'ICD10', code: 'J34.8', description: 'Otros trastornos especificados de la nariz y senos paranasales', chapter: 'J30-J39', parentCode: 'J34' },
  { system: 'ICD10', code: 'J35.0', description: 'Amigdalitis crónica', chapter: 'J30-J39', parentCode: 'J35' },
  { system: 'ICD10', code: 'J35.1', description: 'Hipertrofia de las amígdalas', chapter: 'J30-J39', parentCode: 'J35' },
  { system: 'ICD10', code: 'J35.2', description: 'Hipertrofia de las adenoides', chapter: 'J30-J39', parentCode: 'J35' },
  { system: 'ICD10', code: 'J35.3', description: 'Hipertrofia de amígdalas y adenoides', chapter: 'J30-J39', parentCode: 'J35' },
  { system: 'ICD10', code: 'J35.8', description: 'Otras enfermedades crónicas de amígdalas y adenoides', chapter: 'J30-J39', parentCode: 'J35' },
  { system: 'ICD10', code: 'J35.9', description: 'Enfermedad crónica de amígdalas y adenoides no especificada', chapter: 'J30-J39', parentCode: 'J35' },
  { system: 'ICD10', code: 'J36', description: 'Absceso periamigdalino', chapter: 'J30-J39' },
  { system: 'ICD10', code: 'J37.0', description: 'Laringitis crónica', chapter: 'J30-J39', parentCode: 'J37' },
  { system: 'ICD10', code: 'J37.1', description: 'Laringotraqueítis crónica', chapter: 'J30-J39', parentCode: 'J37' },
  { system: 'ICD10', code: 'J38.0', description: 'Parálisis de cuerdas vocales y laringe', chapter: 'J30-J39', parentCode: 'J38' },
  { system: 'ICD10', code: 'J38.1', description: 'Pólipo de cuerda vocal y laringe', chapter: 'J30-J39', parentCode: 'J38' },
  { system: 'ICD10', code: 'J38.2', description: 'Nódulos de cuerdas vocales', chapter: 'J30-J39', parentCode: 'J38' },
  { system: 'ICD10', code: 'J38.3', description: 'Otras enfermedades de cuerdas vocales', chapter: 'J30-J39', parentCode: 'J38' },
  { system: 'ICD10', code: 'J38.4', description: 'Edema de laringe', chapter: 'J30-J39', parentCode: 'J38' },
  { system: 'ICD10', code: 'J38.5', description: 'Espasmo laríngeo', chapter: 'J30-J39', parentCode: 'J38' },
  { system: 'ICD10', code: 'J38.6', description: 'Estenosis laríngea', chapter: 'J30-J39', parentCode: 'J38' },
  { system: 'ICD10', code: 'J38.7', description: 'Otras enfermedades de la laringe', chapter: 'J30-J39', parentCode: 'J38' },
  { system: 'ICD10', code: 'J39.0', description: 'Absceso retrofaríngeo y parafaríngeo', chapter: 'J30-J39', parentCode: 'J39' },
  { system: 'ICD10', code: 'J39.1', description: 'Otros abscesos de la faringe', chapter: 'J30-J39', parentCode: 'J39' },
  { system: 'ICD10', code: 'J39.2', description: 'Otras enfermedades de la faringe', chapter: 'J30-J39', parentCode: 'J39' },
  { system: 'ICD10', code: 'J39.3', description: 'Reacción de hipersensibilidad de vías respiratorias superiores', chapter: 'J30-J39', parentCode: 'J39' },
  { system: 'ICD10', code: 'J39.8', description: 'Otras enfermedades especificadas de vías respiratorias superiores', chapter: 'J30-J39', parentCode: 'J39' },
  { system: 'ICD10', code: 'J39.9', description: 'Enfermedad de vías respiratorias superiores no especificada', chapter: 'J30-J39', parentCode: 'J39' },

  // J40-J47: Enfermedades crónicas de vías respiratorias inferiores
  { system: 'ICD10', code: 'J44.0', description: 'Enfermedad pulmonar obstructiva crónica con infección aguda de vías respiratorias inferiores', chapter: 'J40-J47', parentCode: 'J44' },
  { system: 'ICD10', code: 'J44.1', description: 'Enfermedad pulmonar obstructiva crónica con exacerbación aguda no especificada', chapter: 'J40-J47', parentCode: 'J44' },
  { system: 'ICD10', code: 'J44.8', description: 'Otras enfermedades pulmonares obstructivas crónicas especificadas', chapter: 'J40-J47', parentCode: 'J44' },
  { system: 'ICD10', code: 'J44.9', description: 'Enfermedad pulmonar obstructiva crónica no especificada', chapter: 'J40-J47', parentCode: 'J44' },
  { system: 'ICD10', code: 'J45.0', description: 'Asma predominantemente alérgica', chapter: 'J40-J47', parentCode: 'J45' },
  { system: 'ICD10', code: 'J45.1', description: 'Asma no alérgica', chapter: 'J40-J47', parentCode: 'J45' },
  { system: 'ICD10', code: 'J45.8', description: 'Asma mixta', chapter: 'J40-J47', parentCode: 'J45' },
  { system: 'ICD10', code: 'J45.9', description: 'Asma no especificada', chapter: 'J40-J47', parentCode: 'J45' },

  // C00-C14, C30-C32: Neoplasias de cabeza y cuello (selección ORL)
  { system: 'ICD10', code: 'C00', description: 'Tumor maligno del labio', chapter: 'C00-C14' },
  { system: 'ICD10', code: 'C01', description: 'Tumor maligno de la base de la lengua', chapter: 'C00-C14' },
  { system: 'ICD10', code: 'C02.0', description: 'Tumor maligno de la cara dorsal de la lengua', chapter: 'C00-C14', parentCode: 'C02' },
  { system: 'ICD10', code: 'C02.1', description: 'Tumor maligno del borde de la lengua', chapter: 'C00-C14', parentCode: 'C02' },
  { system: 'ICD10', code: 'C02.9', description: 'Tumor maligno de la lengua no especificado', chapter: 'C00-C14', parentCode: 'C02' },
  { system: 'ICD10', code: 'C04.0', description: 'Tumor maligno del piso anterior de la boca', chapter: 'C00-C14', parentCode: 'C04' },
  { system: 'ICD10', code: 'C04.9', description: 'Tumor maligno del piso de la boca no especificado', chapter: 'C00-C14', parentCode: 'C04' },
  { system: 'ICD10', code: 'C06.0', description: 'Tumor maligno de la mucosa de la mejilla', chapter: 'C00-C14', parentCode: 'C06' },
  { system: 'ICD10', code: 'C07', description: 'Tumor maligno de la glándula parótida', chapter: 'C00-C14' },
  { system: 'ICD10', code: 'C08.0', description: 'Tumor maligno de la glándula submandibular', chapter: 'C00-C14', parentCode: 'C08' },
  { system: 'ICD10', code: 'C09.0', description: 'Tumor maligno de la fosa amigdalina', chapter: 'C00-C14', parentCode: 'C09' },
  { system: 'ICD10', code: 'C10.0', description: 'Tumor maligno de la vallécula', chapter: 'C00-C14', parentCode: 'C10' },
  { system: 'ICD10', code: 'C11.0', description: 'Tumor maligno de la pared superior de la nasofaringe', chapter: 'C00-C14', parentCode: 'C11' },
  { system: 'ICD10', code: 'C12', description: 'Tumor maligno del seno piriforme', chapter: 'C00-C14' },
  { system: 'ICD10', code: 'C13.0', description: 'Tumor maligno de la región postcricoidea', chapter: 'C00-C14', parentCode: 'C13' },
  { system: 'ICD10', code: 'C14.0', description: 'Tumor maligno de la faringe sitio no especificado', chapter: 'C00-C14', parentCode: 'C14' },
  { system: 'ICD10', code: 'C30.0', description: 'Tumor maligno de la fosa nasal', chapter: 'C30-C32', parentCode: 'C30' },
  { system: 'ICD10', code: 'C30.1', description: 'Tumor maligno del oído medio', chapter: 'C30-C32', parentCode: 'C30' },
  { system: 'ICD10', code: 'C31.0', description: 'Tumor maligno del seno maxilar', chapter: 'C30-C32', parentCode: 'C31' },
  { system: 'ICD10', code: 'C31.1', description: 'Tumor maligno del seno etmoidal', chapter: 'C30-C32', parentCode: 'C31' },
  { system: 'ICD10', code: 'C31.2', description: 'Tumor maligno del seno frontal', chapter: 'C30-C32', parentCode: 'C31' },
  { system: 'ICD10', code: 'C32.0', description: 'Tumor maligno de la glotis', chapter: 'C30-C32', parentCode: 'C32' },
  { system: 'ICD10', code: 'C32.1', description: 'Tumor maligno de la región supraglótica', chapter: 'C30-C32', parentCode: 'C32' },
  { system: 'ICD10', code: 'C32.2', description: 'Tumor maligno de la región subglótica', chapter: 'C30-C32', parentCode: 'C32' },
  { system: 'ICD10', code: 'C32.3', description: 'Tumor maligno del cartílago laríngeo', chapter: 'C30-C32', parentCode: 'C32' },
  { system: 'ICD10', code: 'C32.9', description: 'Tumor maligno de la laringe no especificado', chapter: 'C30-C32', parentCode: 'C32' },

  // Q16-Q18: Malformaciones congénitas de oído/cara
  { system: 'ICD10', code: 'Q16.0', description: 'Ausencia congénita del pabellón auricular', chapter: 'Q16-Q18', parentCode: 'Q16' },
  { system: 'ICD10', code: 'Q16.1', description: 'Ausencia o estenosis congénita del conducto auditivo externo', chapter: 'Q16-Q18', parentCode: 'Q16' },
  { system: 'ICD10', code: 'Q16.3', description: 'Malformación congénita de los huesecillos del oído', chapter: 'Q16-Q18', parentCode: 'Q16' },
  { system: 'ICD10', code: 'Q16.4', description: 'Otras malformaciones congénitas del oído medio', chapter: 'Q16-Q18', parentCode: 'Q16' },
  { system: 'ICD10', code: 'Q16.5', description: 'Malformación congénita del oído interno', chapter: 'Q16-Q18', parentCode: 'Q16' },
  { system: 'ICD10', code: 'Q16.9', description: 'Malformación congénita del oído no especificada', chapter: 'Q16-Q18', parentCode: 'Q16' },
  { system: 'ICD10', code: 'Q17.0', description: 'Oreja supernumeraria', chapter: 'Q16-Q18', parentCode: 'Q17' },
  { system: 'ICD10', code: 'Q17.1', description: 'Macrotia', chapter: 'Q16-Q18', parentCode: 'Q17' },
  { system: 'ICD10', code: 'Q17.2', description: 'Microtia', chapter: 'Q16-Q18', parentCode: 'Q17' },
  { system: 'ICD10', code: 'Q17.3', description: 'Otras deformidades congénitas del pabellón auricular', chapter: 'Q16-Q18', parentCode: 'Q17' },
  { system: 'ICD10', code: 'Q17.8', description: 'Otras malformaciones congénitas especificadas del oído', chapter: 'Q16-Q18', parentCode: 'Q17' },
  { system: 'ICD10', code: 'Q18.0', description: 'Seno, fístula o quiste de la hendidura branquial', chapter: 'Q16-Q18', parentCode: 'Q18' },
  { system: 'ICD10', code: 'Q18.1', description: 'Seno y quiste preauricular', chapter: 'Q16-Q18', parentCode: 'Q18' },
  { system: 'ICD10', code: 'Q18.8', description: 'Otras malformaciones congénitas especificadas de cara y cuello', chapter: 'Q16-Q18', parentCode: 'Q18' },

  // D10-D36, D14: Neoplasias benignas de cabeza y cuello
  { system: 'ICD10', code: 'D10.0', description: 'Tumor benigno del labio', chapter: 'D10-D36', parentCode: 'D10' },
  { system: 'ICD10', code: 'D10.1', description: 'Tumor benigno de la lengua', chapter: 'D10-D36', parentCode: 'D10' },
  { system: 'ICD10', code: 'D10.6', description: 'Tumor benigno de la nasofaringe', chapter: 'D10-D36', parentCode: 'D10' },
  { system: 'ICD10', code: 'D11.0', description: 'Tumor benigno de la glándula parótida', chapter: 'D10-D36', parentCode: 'D11' },
  { system: 'ICD10', code: 'D14.0', description: 'Tumor benigno del oído medio, cavidad nasal y senos paranasales', chapter: 'D10-D36', parentCode: 'D14' },
  { system: 'ICD10', code: 'D14.1', description: 'Tumor benigno de la laringe', chapter: 'D10-D36', parentCode: 'D14' },
  { system: 'ICD10', code: 'D36.1', description: 'Tumor benigno de nervios periféricos y sistema nervioso autónomo', chapter: 'D10-D36', parentCode: 'D36' },
];

export default icd10Catalog;
