// apps/api/src/application/research/export/r-syntax.generator.ts
// Generates an `.R` script reproducing the analyses performed by the
// research engine (M7). Maps each performed test → canonical R call:
//   ttest_independent → t.test(group1, group2, var.equal=FALSE)
//   mannwhitney        → wilcox.test(group1, group2)
//   chi_square         → chisq.test(matrix)
//   fisher_exact       → fisher.test(matrix)
//   kruskalwallis      → kruskal.test(...)
//   pearson/spearman   → cor.test(x, y, method=...)
//   linear_regression  → lm(y ~ x)
//   logistic_regression→ glm(y ~ x, family=binomial)
//   kaplan_meier       → survfit(Surv(time, event) ~ 1); survdiff(...)
// Pure (no I/O) — receives a list of performed-test descriptors → R string.

export type RSupportedTest =
  | 'ttest_independent' | 'mannwhitney' | 'chi_square' | 'fisher_exact'
  | 'kruskalwallis' | 'pearson' | 'spearman'
  | 'linear_regression' | 'logistic_regression' | 'kaplan_meier';

export interface RSynRequestTest {
  test: RSupportedTest;
  /** identifier name for the dataset / variable (sanitized) */
  group1?: string;
  group2?: string;
  xField?: string;
  yField?: string;
  timeField?: string;
  eventField?: string;
  /** extra nuance: heteroscedastic t-test? */
  varEqual?: boolean;
}

export interface RSynRequest {
  studyName?: string;
  tests: RSynRequestTest[];
}

const HEADER = (name: string | undefined) =>
  `# R script — Medicore research export
# Study: ${name ?? '(unnamed)'}
# Generated by the research engine (M7). Reproduce with: source("this-file.R")
library("survival")

`;

/** Sanitize a name into a valid R identifier. */
function id(s: string | undefined): string {
  if (!s) return 'x';
  const cleaned = String(s).replace(/[^A-Za-z0-9_\\.]/g, '_').replace(/^([0-9])/, '_$1');
  return cleaned || 'x';
}

function line(t: RSynRequestTest): string {
  switch (t.test) {
    case 'ttest_independent':
      return `t.test(${id(t.group1)}, ${id(t.group2)}, var.equal = ${t.varEqual === true ? 'TRUE' : 'FALSE'})`;
    case 'mannwhitney':
      return `wilcox.test(${id(t.group1)}, ${id(t.group2)})`;
    case 'chi_square':
      return `chisq.test(observed_matrix)  # group1=${id(t.group1)} group2=${id(t.group2)}`;
    case 'fisher_exact':
      return `fisher.test(observed_matrix)  # group1=${id(t.group1)} group2=${id(t.group2)}`;
    case 'kruskalwallis':
      return `kruskal.test(outcome ~ group)`;
    case 'pearson':
      return `cor.test(${id(t.xField)}, ${id(t.yField)}, method = "pearson")`;
    case 'spearman':
      return `cor.test(${id(t.xField)}, ${id(t.yField)}, method = "spearman")`;
    case 'linear_regression':
      return `lm(${id(t.yField)} ~ ${id(t.xField)}, data = df)`;
    case 'logistic_regression':
      return `glm(${id(t.yField)} ~ ${id(t.xField)}, data = df, family = binomial(link = "logit"))`;
    case 'kaplan_meier':
      return `survfit(Surv(${id(t.timeField)}, ${id(t.eventField)}) ~ 1, data = df)\nsurvdiff(Surv(${id(t.timeField)}, ${id(t.eventField)}) ~ group, data = df)`;
    default:
      return `# unsupported: ${t.test}`;
  }
}

export function generateRSyntax(req: RSynRequest): string {
  const body = req.tests.map((t, i) => `# Test ${i + 1}: ${t.test}\n${line(t)}`).join('\n\n');
  return `${HEADER(req.studyName)}${body}\n`;
}